### ISSUE TITLE
Passive scroll listener

### ISSUE THREAD

**Issue by tk-o** [NomanGul/react-page-progress#2]
Scroll event listener triggers lots of time during. Would be awesome to wrap that listener with [a throttle function](https://codeburst.io/throttling-and-debouncing-in-javascript-b01cad5c8edf#fb88).

**Comment by NomanGul** [comment]
@kopacki awesome. I'll work on this.

Do you've another suggestion?

**Comment by tk-o** [comment]
Actually, one. You may want to move the source code into [`create-react-library`](https://www.npmjs.com/package/create-react-library), as your component is actually served as a library.
