### ISSUE TITLE
Question: Is this compatible with Gatsby JS? 

### ISSUE THREAD

**Issue by drailanjohngss** [NomanGul/react-page-progress#4]
I'm trying to use it with Gatsby JS ? 
![image](https://user-images.githubusercontent.com/31638171/52943105-54657100-33a7-11e9-9a13-2788bb2d13d1.png)

But I have encountered an error.

**Comment by NomanGul** [comment]
@drailanjohngss Brother, I don't know because I'm not familiar with gatsby :(
